services:
  - type: web
    name: chatbot-mama-render
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free          # Puedes cambiar a 'starter' si quieres que no se duerma
    branch: main
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    healthCheckPath: "/"
    disk:
      name: data
      mountPath: /app
      sizeGB: 1